import React, { useState, useContext, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { AuthContext } from '../context/AuthContext';
import { toast } from 'react-toastify';

const Login = () => {
  const { user, login, register } = useContext(AuthContext);
  const [isRegisterMode, setIsRegisterMode] = useState(false);

  // Form States
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [role, setRole] = useState('EMPLOYEE');
  const [employeeCode, setEmployeeCode] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const navigate = useNavigate();
  const location = useLocation();

  // Redirect if already logged in
  useEffect(() => {
    if (user) {
      navigate('/dashboard');
    }
  }, [user, navigate]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!username || !password) {
      toast.error('Please enter both username and password.');
      return;
    }

    setIsLoading(true);

    if (isRegisterMode) {
      if (role === 'EMPLOYEE' && !employeeCode) {
        toast.error('Employee Code is required for Employee accounts.');
        setIsLoading(false);
        return;
      }

      const res = await register(username, password, role, employeeCode);
      if (res.success) {
        toast.success('Registration successful! Please login.');
        setIsRegisterMode(false);
        setPassword('');
      } else {
        toast.error(res.error);
      }
    } else {
      const res = await login(username, password);
      if (res.success) {
        toast.success('Welcome back!');
        const origin = location.state?.from?.pathname || '/';
        navigate(origin);
      } else {
        toast.error(res.error);
      }
    }

    setIsLoading(false);
  };

  return (
    <div className="login-container">
      <div className="login-card">
        <div className="text-center mb-4">
          <i className="bi bi-wallet2 text-teal-primary" style={{ fontSize: '3rem' }}></i>
          <h3 className="text-white mt-2 fw-bold">Vertex Payroll</h3>
          <p className="text-muted" style={{ fontSize: '0.85rem' }}>
            {isRegisterMode ? 'Create a new user account' : 'Sign in to access your portal'}
          </p>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="mb-3">
            <label className="form-label">Username</label>
            <input
              type="text"
              className="form-control"
              placeholder="Enter username"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
            />
          </div>

          <div className="mb-3">
            <label className="form-label">Password</label>
            <input
              type="password"
              className="form-control"
              placeholder="Enter password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </div>

          {isRegisterMode && (
            <>
              <div className="mb-3">
                <label className="form-label">Account Role</label>
                <select
                  className="form-select"
                  value={role}
                  onChange={(e) => setRole(e.target.value)}
                >
                  <option value="EMPLOYEE">Employee</option>
                  <option value="ADMIN">Administrator</option>
                </select>
              </div>

              {role === 'EMPLOYEE' && (
                <div className="mb-3">
                  <label className="form-label">Employee Code</label>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="e.g. EMP001"
                    value={employeeCode}
                    onChange={(e) => setEmployeeCode(e.target.value)}
                    required
                  />
                  <small className="text-muted" style={{ fontSize: '0.75rem' }}>
                    Must match the employee code generated by HR.
                  </small>
                </div>
              )}
            </>
          )}

          <button type="submit" className="btn btn-teal w-100 mt-2 py-2" disabled={isLoading}>
            {isLoading ? (
              <span className="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
            ) : null}
            {isRegisterMode ? 'Register Account' : 'Sign In'}
          </button>
        </form>

        <div className="text-center mt-4">
          <button
            onClick={() => setIsRegisterMode(!isRegisterMode)}
            className="btn btn-link text-teal-primary text-decoration-none"
            style={{ fontSize: '0.9rem' }}
          >
            {isRegisterMode ? 'Already have an account? Sign In' : "Don't have an account? Register"}
          </button>
        </div>
      </div>
    </div>
  );
};

export default Login;
